-- 1. Index on StudentID and SectionID for Enrollments (Covering index pattern)
CREATE NONCLUSTERED INDEX IX_Enrollments_StudentID_SectionID 
ON Enrollments (StudentID, SectionID)
INCLUDE (EnrollDate, Status);
GO
-- 2. Index on FeePayments PaymentDate
CREATE NONCLUSTERED INDEX IX_FeePayments_PaymentDate 
ON FeePayments (PaymentDate)
INCLUDE (StudentID, AmountPaid);
GO
-- 3. Filtered Index on LibraryIssues for unreturned items (optimizes overdue checks)
CREATE NONCLUSTERED INDEX IX_LibraryIssues_ReturnDate_Filtered 
ON LibraryIssues (ReturnDate)
INCLUDE (StudentID, ItemID, DueDate)
WHERE ReturnDate IS NULL;
GO
-- 4. Covering Index on AttendanceRecords for calculating attendance percentage
CREATE NONCLUSTERED INDEX IX_AttendanceRecords_StudentID_Date_Covering
ON AttendanceRecords (EnrollmentID, Date)
INCLUDE (Status);
GO
-- 5. Non-clustered Index on Students ProgramID
CREATE NONCLUSTERED INDEX IX_Students_ProgramID 
ON Students (ProgramID)
INCLUDE (FirstName, LastName, CurrentSemester);
GO
-- 6. Setup Full-Text Indexing on LibraryItems table covering Title and Author
-- Create Full-Text Catalog
IF NOT EXISTS (SELECT 1 FROM sys.fulltext_catalogs WHERE name = 'ftc_HiSUP_Library')
BEGIN
    CREATE FULLTEXT CATALOG ftc_HiSUP_Library AS DEFAULT;
END;
GO
-- Create Full-Text Index (assumes ItemID is the unique primary key constraint index)
-- In SQL Server, we must obtain the primary key constraint name. For our table it is PK__LibraryI__....
-- But since constraint names generated by PRIMARY KEY are random unless named, we find or name it.
-- Let's drop the table if we want to name it PK_LibraryItems_ItemID, but we can also just name it in create_indexes.sql or assume the index is there.
-- Let's verify: we can find the name of the PK index, or create a unique key just for it, or we can check sys.indexes.
-- Let's declare the fulltext index by referencing the primary key index name. Wait! We can retrieve the name dynamically or use a named index.
-- Since the master script names tables, let's look at HiSUP_DB_Script.sql. We did NOT explicitly name the PK constraint, it's just 'PRIMARY KEY IDENTITY'.
-- That's okay! We can alter the table to add a named unique constraint, or we can define a named primary key in HiSUP_DB_Script.sql.
-- Let's alter the table in create_indexes.sql or write it dynamically.
-- Let's check: we can use a dynamic SQL approach to create the fulltext index on LibraryItems using its PK:
DECLARE @PKName NVARCHAR(200);
SELECT TOP 1 @PKName = name 
FROM sys.indexes 
WHERE object_id = OBJECT_ID('LibraryItems') AND is_primary_key = 1;
DECLARE @SQL NVARCHAR(MAX);
SET @SQL = 'CREATE FULLTEXT INDEX ON LibraryItems(Title, Author) KEY INDEX [' + @PKName + '] ON ftc_HiSUP_Library WITH CHANGE_TRACKING AUTO;';
EXEC sp_executesql @SQL;
GO
